import { Open_Sans, Lora, Cinzel, Noto_Sans } from "next/font/google";
import "@/globals.css";
import Header from "../../components/shared-components/header/Header";
import {getData} from '@/utils/serverActions'
import {API_BASE_URL,IMG_BASE_URL, API_ENDPOINTS} from '@/api/apiConfig'



 const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
})

 const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-opensans",
})

 const cinzel = Cinzel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cinzel",
})

 const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ['300', '400', '700'],
  variable: "--font-noto",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function AboutLayout({ children,params }) {
  'use server'
  const data = await getData(API_BASE_URL,API_ENDPOINTS.PAGES)

  return (
    <section className={`section-snap ${lora.variable} ${opensans.variable} ${cinzel.variable} ${noto.variable}`} style={{ minHeight: '100vh', position: 'relative' }}>

    <Header data={data} />
      {
        children
      }
    </section>
  );
}
