import { Open_Sans, Lora, Cinzel, Noto_Sans } from "next/font/google";
import "../globals.css";
import Header from "../components/shared-components/header/Header";




export const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
})

export const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-opensans",
})

export const cinzel = Cinzel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cinzel",
})

export const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ['300', '400', '700'],
  variable: "--font-noto",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function AboutLayout({ children }) {
  return (
    <section className='section' style={{ minHeight: '100vh', position: 'relative' }}>

    <Header/>
      {
        children
      }
    </section>
  );
}
