import { Providers } from "@/Theme.tsx";
import "@/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { i18n, Locale } from "../../i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}



export default function RootLayout({   children,
  params, }) {
  return (
    <html lang={params.locale}  >
      <body className={`body`}>
        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  );
}
